### ISSUE TITLE
Server Replikation

### ISSUE THREAD

**Issue by nsommer** [llgb/chatVS#2]
# Diskussions Thread u. Fortschrittsinfos

Es soll die _Master/Slave_ Replikation von **MYSQL** verwendet werden.
## Linksammlung Master/Slave Replikation
- [https://dev.mysql.com/doc/refman/5.0/en/replication-howto.html](https://dev.mysql.com/doc/refman/5.0/en/replication-howto.html)
- [https://www.thomas-krenn.com/de/wiki/MySQL_Replikation](https://www.thomas-krenn.com/de/wiki/MySQL_Replikation)
## Servermanagement

Mit commit 167665f14f554c4333fc54de120f1d3882bfddbd wurde die Klasse `ServerManager` eingeführt, welche für Datenbankverbindungen verwendet wird. Die Klasse kann mehrere jdbc URLs speichern, die aktuelle (Default) ausgeben sowie die aktuelle Verbindung wechseln.

Die Instanz dieser Klasse kann entweder dynamisch durch einen Methodenaufruf neue Verbindungs-URLs bekommen und/oder zu Beginn aus einer Textdatei lesen.
### Server hinzufügen/entfernen

Es soll eine neue Tabelle im Datenbankschema erstellt werden, welche **IP** und **Port** jeder bekannten Datenbank, die Teil der Replikation ist, speichert. Somit würden die zur Verfügung stehenden Datenbanken auch automatisch über alle Datenbanken synchronisiert (repliziert) werden und könnten zur Laufzeit der Chatapplikation ausgelesen werden (Initialisierung und/oder Ändern der ServerManager Instanz).

Subissue: #3.
## Schaubild

![mysql-replikation-chat](https://cloud.githubusercontent.com/assets/5717791/7332786/f6ae2224-eb51-11e4-8b4c-50dd4f37e075.jpg)

**Comment by nsommer** [comment]
Mit commit 70637e48e3b8e571b5b717ce45ad387b1079624e wurde die Synchronisation mit der Datenbank zum Abgleich aller bekannten Hosts implementiert. Diese wird derzeit noch nicht aktiv aufgerufen, jedoch sollte - nach dem erweitern des Datenbankschemas gemäß der Änderungen des `createTables.sql` Skripts - schon mal folgende SQL Befehle ausgeführt werden um die lokale Datenbank bekannt zu machen:

``` sql
mysql> insert into servers values (default,'localhost',NULL);
Query OK, 1 row affected (0,00 sec)

mysql> select * from servers;
+----+-----------+------+
| id | host      | port |
+----+-----------+------+
|  1 | localhost | NULL |
+----+-----------+------+
1 row in set (0,00 sec)
```

**Comment by llgb** [comment]
Welcher Server-IDs hast du bei dir vergeben? 
Wollen wir Nummerkreise nehmen, so dass Du für deine Server den Bereich 2x (also 20-29) bekommst und ich 3x nehme? 
Der Master könnte dann die ID 10 bekommen.
Also nur, falls du nicht schon was gemacht hast. Falls schon was vergeben ist würde ich IDs nehmen die frei sind.

**Comment by nsommer** [comment]
Wird geschlossen aufgrund des Umstiegs zu CouchDB.
